[workspace]
resolver = "3"
members = ["crates/*"]
default-members = ["crates/weshtatistic"]

[workspace.package]
version = "2.2.0"
edition = "2024"
license = "MIT"
authors = ["weshford"]
repository = "https://github.com/weshford/weshtatistic"

[patch.crates-io]
winit = { git = "https://github.com/xangelix/winit.git", branch = "blur-fix" }
# egui-table-kit = { path = "../egui-table-kit" }

[profile.release]
panic = "abort"
strip = true
lto = "thin"
# debug = true
codegen-units = 1
