[package]
name = "weshtatistic"
description = "A fast, cross-platform disk usage analyzer and deduplicator—with work-stealing multithreading, zero-copy snapshots, and an interactive treemap GUI."
version.workspace = true
edition.workspace = true
license.workspace = true
documentation = "https://docs.rs/weshtatistic"
readme = "../../README.md"
repository.workspace = true
authors.workspace = true
categories = [
    "gui",
    "filesystem",
    "visualization",
    "concurrency",
    "memory-management",
]
keywords = ["disk-usage", "treemap", "egui", "dirstat", "zero-copy"]

include = [
    "/Cargo.toml",
    "/src/**/*",
    "/assets/**/*",
    "/build.rs",
    "/LICENSE",
]

[features]
default = ["online"]
online = ["weshtatistic-gui/online"]
profile-tracy = ["tracy-client", "weshtatistic-gui/profile-tracy"]

[dependencies]
weshtatistic-core = { path = "../weshtatistic-core", version = "2.2.0" }
weshtatistic-gui = { path = "../weshtatistic-gui", version = "2.2.0", default-features = false }

ahash = "0.8.12"
anyhow = "1.0.104"
bytemuck = { version = "1.25.2", features = ["derive"] }
clap = { version = "4.6.7", features = ["derive"] }
cli-or-gui = "0.1.1"
compact_str = "0.10.0"
crc-fast = "1.10.0"
crossbeam = "0.8.5"
eframe = "0.36.2"
mimalloc-rspack = { version = "0.2.4", features = ["v3"] }
parking_lot = { version = "0.12.5", features = ["hardware-lock-elision"] }
rayon = "1.12.0"
serde_json = "1.0.151"
smallvec = "1.16.1"
sysinfo = { version = "0.39.6", default-features = false, features = ["disk"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = [
    "Win32_Foundation",
    "Win32_Storage_FileSystem",
] }

# feature: profile-tracy
tracy-client = { version = "0.19.0", optional = true }

[build-dependencies]
winresource = "0.1.31"

[[bin]]
name = "weshtatistic"
path = "src/bin/weshtatistic.rs"

[[bench]]
name = "compare"
harness = false
path = "benches/compare.rs"

[[bench]]
name = "mft_bench"
harness = false

[dev-dependencies]
criterion = "0.8.2"
